### ISSUE TITLE
Support Weekly Schedule

### ISSUE THREAD

**Issue by lukasf98** [Lavisx/lidl-valve-z2m#1]
I've looked in the logs and it seems that the weekly schedule is transmitted in the following way:

[day_of_week, temperature * 2, time_in_hours * 4, ...]
Example: [1, 34, 1, 34, 96, 34, 68, 42, 92, 34, 96, 42, 96, 34, 96, 42, 96, 34]
Translated: [Monday, 17°, 0:15, 17°, 24:00, ... ]

Note: day_of_week ist starting with Monday (0) and ending with Sunday (7).
It would be great if that could be added and also sending weekly schedules to the valve.

**Comment by Lavisx** [comment]
Now is added base stupid scheduling. I don't know how use array structure to expose to UI so it now use simple flat and stupid variables name.

**Comment by lukasf98** [comment]
Great! Thanks a lot!

I tested it and I have one problem that I can't change the times. Is that just an issue on my side or haven't you implemented it yet?

**Comment by Lavisx** [comment]
When you change the times and click apply so it will send the new values.
There is some issue in UI.
I opened new issue https://github.com/Koenkk/zigbee2mqtt/issues/9096

**Comment by lukasf98** [comment]
You're right. It works when I click apply.
