### ISSUE TITLE
Error: No converter available for 'local_temperature' ()

### ISSUE THREAD

**Issue by schluese** [Lavisx/lidl-valve-z2m#2]
Unfortunately, I still get the following errors, am I doing something wrong?

Zigbee2MQTT:debug 2021-10-20 17:50:47: Received MQTT message on 'zigbee2mqtt/0x0c4314fffe619ef4/get' with data '{"local_temperature":""}'
Zigbee2MQTT:error 2021-10-20 17:50:47: No converter available for 'local_temperature' ()

thanks for your effort :-)

**Comment by Lavisx** [comment]
In which situation you are receive this error? 
Have you full data from device if this is received from device?
Or this mean set the local_temperature to device? This is not available.
It's also weird that the value is empty.

**Comment by schluese** [comment]
I get the error when I want to update the local temperature, it had a wrong value. overlooked the calibration.  sorry!
now everything seems to be working out.
Thanks again
