### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by Element2** [Lavisx/lidl-valve-z2m#5]
Hi,

Is this still being developed?
Since the default z2m convertor for the 368308_2010 _TZE200_chyvmay  does nothing with the 'away' and local program day values, I was wondering if this code does. Looking at the code it looks it does.
Unfortunately it isn't working with z2m if I add it as an external convertor.

**Comment by Lavisx** [comment]
I'm sorry but I don't continue in developing from time when it was implemented to z2m natively.
